name: Build & Release

# This workflow is triggered on pushes to the repository.
on:

  push:
    branches:
    - main
    - master
    - develop
    
# on: push    # Default will running for every branch.


    
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          token-endpoint: http://122.54.198.84:82/api/auth/get_token
          token-configuration: '{ "method": "POST", "body": {"username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}" } }'
          # Once the token endpoint has fetched then this endpoint is requested.
          endpoint: http://122.54.198.84:82/api/f_e/version/add_update
          # The bearer token here is returned from the TOKEN_ENDPOINT call. The returned data looks like so: {data: {access_token: '123'}}, meaning it can be accessed using the triple bracket syntax.
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer {{{ data.token }}}"}, "body": {"platform": "android", "version": "1.0.0", "buildNumber": 2, "packageName": "com.delicious_ordering.android.app", "releaseNotes": "Minor updates and improvements."} }'
 
